name: Deploy to ECR

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build MySQL image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/mysql-ecr:latest -f mysql/Dockerfile .

      - name: Push MySQL image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/mysql-ecr:latest

      - name: Build Webapp image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/webapp-ecr:latest .

      - name: Push Webapp image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/webapp-ecr:latest
